name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v1
      - name: Make temp file
        run: |
          echo "Before $(pwd)"
          cd ~/; echo "After $(pwd)"
          mkdir ~/tempfile
          echo "test" >> ~/tempfile/test
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/tempfile
          key: ${{ runner.os }}-tempfile-${{ hashFiles('**/tempfile') }}
          restore-keys: |
            ${{ runner.os }}-tempfile-
    
      
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/tempfile
          key: ${{ runner.os }}-tempfile-${{ hashFiles('**/tempfile') }}
          restore-keys: |
            ${{ runner.os }}-tempfile-

      - name: Run SonarCloud analyse
        run: |
          echo "Current : $(pwd)";
          ls -al ~/
          cat ~/tempfile/test
